### ISSUE TITLE
Document where to find the different counties' forms

### ISSUE THREAD

**Issue by fureigh** [fureigh/change-my-record#11]
As of this writing, about two dozen counties' forms are listed at http://www.safeandjust.org/recordchange, out of a total of 58 California counties. @nikzei had a great idea to crowdsource collection of the forms, including identifying which counties are using others' forms, so I'm capturing it here. :)

**Skills required:** internet research, spreadsheet or wiki page creation/curation, possibly calling courts.

**Update:** You can [add them to this spreadsheet](https://docs.google.com/spreadsheets/d/1zQ7HqKrzM6d1SIIdPItlr_Z_YWOvc11X_Cp1tlr4t5s/edit?usp=sharing)!

**Comment by fureigh** [comment]
Will be useful to and referenced in #10.

**Comment by alanjosephwilliams** [comment]
Have you seen https://github.com/codeforamerica/project-ideas/issues/44?

Definitely out of scope, but worth reading the issue, and keeping in the
back of your mind whether your work collecting forms could beat a trail
that could be followed by others.

On Mon, Mar 16, 2015 at 2:05 PM, Fureigh <notifications@github.com> wrote:

> Will be useful to and referenced in #10
> <https://github.com/codeforamerica/re-record/issues/10>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codeforamerica/re-record/issues/11#issuecomment-81938943>
> .
>



-- 
t:  @alanjosephwilli
p: 817 713 6264

**Comment by fureigh** [comment]
@alanjosephwilliams Have seen, and I'm very curious to see where it goes. When I see All Your Forms I think of a web scraper pulling all fillable PDFs from .gov sites — I just left a comment to that effect, thanks for prompting— but can you say a bit more about the kind of trail you're envisioning? A guide to manually spelunking for forms, or...?

**Comment by nikzei** [comment]
Here's a start - there are still pdfs from http://www.safeandjust.org/recordchange that haven't been entered yet;):
https://docs.google.com/spreadsheets/d/1zQ7HqKrzM6d1SIIdPItlr_Z_YWOvc11X_Cp1tlr4t5s/edit?usp=sharing

**Comment by fureigh** [comment]
@nikzei Awesome! Thanks for getting that started.

**Comment by fureigh** [comment]
Update: Californians for Safety and Justice has posted even more of them, along with public defender and courthouse contact info, as this [county map](http://www.safeandjust.org/county-map).
