### ISSUE TITLE
Transfer to @fureigh's account

### ISSUE THREAD

**Issue by daguar** [fureigh/change-my-record#14]

**Comment by daguar** [comment]
Transfer request made

**Comment by fureigh** [comment]
:crickets: Maybe we broke GitHub.

**Comment by daguar** [comment]
Just aborted it and re-sent. Check now?

**Comment by daguar** [comment]
Currently it says the transfer is pending (see below), so maybe check your spam folder?

![screen shot 2015-03-21 at 9 18 27 am](https://cloud.githubusercontent.com/assets/994938/6765773/4cd827c0-cfab-11e4-95b5-770960a09422.png)

**Comment by fureigh** [comment]
All set now. Thanks, @daguar!
